module.exports = {
  TAGS_BLACKLIST: {
    '2020': true,
    scfirst: true,
    getmoreplays: true,
    top: true,
  },
  SONG_NAME_DELIMITERS: [
    '(',
    'prod ',
    'feat ',
    'feat.',
    'ft ',
    'ft.',
    'prod by',
    'prod by.',
    'x',
    '[',
  ],
  GENRE_CHARTS_BLACKLIST: {
    'Religion & Spirituality': true,
    Audiobooks: true,
    Business: true,
    Comedy: true,
    Entertainment: true,
    Learning: true,
    'News & Politics': true,
    Science: true,
    Sports: true,
    Storytelling: true,
    Technology: true,
  },
  EXPLORE_RELATED: {
    // how many of the most recent user favorites will be used to as user_input_tracks;
    // this is to avoid getting tracks related to older favorites
    MAX_RECENT_FAVORITES_TRACKS: 20,
    MAX_SOURCE_TRACKS: 10,
    MAX_USER_SOURCE_TRACKS: 10, // do not use the trending tracks at all if user has enough favorites
    MIN_PLAYBACK_COUNT: 1000,
  },
  EMOJI_FLAGS: {
    US: '🇺🇸',
    IN: '🇮🇳',
    TH: '🇹🇭',
    PK: '🇵🇰',
    MX: '🇲🇽',
    DE: '🇩🇪',
    EG: '🇪🇬',
    PE: '🇵🇪',
  },
  IG_POST_COUNTRIES: ['US', 'IN', 'TH', 'PK', 'MX'],
  DISCOVERY_COUNTRIES: {
    IN: 'India',
    PK: 'Pakistan',
    EG: 'Egypt',
    MX: 'Mexico',
    PE: 'Peru',
    TH: 'Thailand',
    DE: 'Germany',
    US: 'United States',
  },
  WRAPPED_YEAR_MONTH: [11],
  COUNTRY_PROMOTION: {
    // BR: {
    //   ctaUrl: 'http://www.splitcloud-app.com/promo_BR.html',
    // },
  },
  TOP_COUNTRIES: {
    IN: 'India',
    PK: 'Pakistan',
    MX: 'Mexico',
    MA: 'Morocco',
    DE: 'Germany',
    ID: 'Indonesia',
    DZ: 'Algeria',
    US: 'United States',
    EG: 'Egypt',
    TH: 'Thailand',
    IT: 'Italy',
    BR: 'Brazil',
    AR: 'Argentina',
    CO: 'Colombia',
    LK: 'Sri Lanka',
    NP: 'Nepal',
    SA: 'Saudi Arabia',
    FR: 'France',
    ES: 'Spain',
    PE: 'Peru',
    CL: 'Chile',
    AE: 'United Arab Emirates',
    IR: 'Iran',
    BD: 'Bangladesh',
    EC: 'Ecuador',
    GB: 'United Kingdom',
    RU: 'Russia',
  },
  SUPPORTED_UNICODE_SCRIPTS: [
    { name: 'latin', regexp: /\p{Script=Latin}/u },
    { name: 'arabic', regexp: /\p{Script=Arabic}/u },
    { name: 'armenian', regexp: /\p{Script=Armenian}/u },
    { name: 'cyrillic', regexp: /\p{Script=Cyrillic}/u },
    { name: 'greek', regexp: /\p{Script=Greek}/u },
    { name: 'thai', regexp: /\p{Script=Thai}/u },
    { name: 'han', regexp: /\p{Script=Han}/u },
  ],
  RADIO_COUNTRY_CODES: [
    { name: 'AD', value: 'AD', stationcount: '5' },
    { name: 'AE', value: 'AE', stationcount: '24' },
    { name: 'AF', value: 'AF', stationcount: '6' },
    { name: 'AG', value: 'AG', stationcount: '3' },
    { name: 'AI', value: 'AI', stationcount: '1' },
    { name: 'AL', value: 'AL', stationcount: '13' },
    { name: 'AM', value: 'AM', stationcount: '33' },
    { name: 'AO', value: 'AO', stationcount: '14' },
    { name: 'AR', value: 'AR', stationcount: '275' },
    { name: 'AS', value: 'AS', stationcount: '1' },
    { name: 'AT', value: 'AT', stationcount: '225' },
    { name: 'AU', value: 'AU', stationcount: '257' },
    { name: 'AW', value: 'AW', stationcount: '17' },
    { name: 'AZ', value: 'AZ', stationcount: '3' },
    { name: 'BA', value: 'BA', stationcount: '38' },
    { name: 'BB', value: 'BB', stationcount: '8' },
    { name: 'BD', value: 'BD', stationcount: '15' },
    { name: 'BE', value: 'BE', stationcount: '207' },
    { name: 'BF', value: 'BF', stationcount: '1' },
    { name: 'BG', value: 'BG', stationcount: '99' },
    { name: 'BH', value: 'BH', stationcount: '1' },
    { name: 'BI', value: 'BI', stationcount: '1' },
    { name: 'BM', value: 'BM', stationcount: '10' },
    { name: 'BN', value: 'BN', stationcount: '1' },
    { name: 'BO', value: 'BO', stationcount: '17' },
    { name: 'BQ', value: 'BQ', stationcount: '6' },
    { name: 'BR', value: 'BR', stationcount: '611' },
    { name: 'BS', value: 'BS', stationcount: '11' },
    { name: 'BW', value: 'BW', stationcount: '2' },
    { name: 'BY', value: 'BY', stationcount: '70' },
    { name: 'CA', value: 'CA', stationcount: '976' },
    { name: 'CD', value: 'CD', stationcount: '6' },
    { name: 'CG', value: 'CG', stationcount: '2' },
    { name: 'CH', value: 'CH', stationcount: '460' },
    { name: 'CI', value: 'CI', stationcount: '12' },
    { name: 'CK', value: 'CK', stationcount: '1' },
    { name: 'CL', value: 'CL', stationcount: '92' },
    { name: 'CM', value: 'CM', stationcount: '2' },
    { name: 'CN', value: 'CN', stationcount: '2018' },
    { name: 'CO', value: 'CO', stationcount: '214' },
    { name: 'CR', value: 'CR', stationcount: '27' },
    { name: 'CU', value: 'CU', stationcount: '4' },
    { name: 'CV', value: 'CV', stationcount: '13' },
    { name: 'CW', value: 'CW', stationcount: '10' },
    { name: 'CY', value: 'CY', stationcount: '34' },
    { name: 'CZ', value: 'CZ', stationcount: '173' },
    { name: 'DE', value: 'DE', stationcount: '2777' },
    { name: 'DK', value: 'DK', stationcount: '67' },
    { name: 'DM', value: 'DM', stationcount: '3' },
    { name: 'DO', value: 'DO', stationcount: '33' },
    { name: 'DZ', value: 'DZ', stationcount: '46' },
    { name: 'EC', value: 'EC', stationcount: '207' },
    { name: 'EE', value: 'EE', stationcount: '56' },
    { name: 'EG', value: 'EG', stationcount: '35' },
    { name: 'ES', value: 'ES', stationcount: '615' },
    { name: 'FI', value: 'FI', stationcount: '139' },
    { name: 'FJ', value: 'FJ', stationcount: '6' },
    { name: 'FK', value: 'FK', stationcount: '1' },
    { name: 'FO', value: 'FO', stationcount: '6' },
    { name: 'FR', value: 'FR', stationcount: '1667' },
    { name: 'GA', value: 'GA', stationcount: '1' },
    { name: 'GB', value: 'GB', stationcount: '737' },
    { name: 'GD', value: 'GD', stationcount: '8' },
    { name: 'GE', value: 'GE', stationcount: '22' },
    { name: 'GF', value: 'GF', stationcount: '1' },
    { name: 'GH', value: 'GH', stationcount: '10' },
    { name: 'GI', value: 'GI', stationcount: '2' },
    { name: 'GL', value: 'GL', stationcount: '2' },
    { name: 'GM', value: 'GM', stationcount: '6' },
    { name: 'GN', value: 'GN', stationcount: '6' },
    { name: 'GP', value: 'GP', stationcount: '9' },
    { name: 'GR', value: 'GR', stationcount: '325' },
    { name: 'GT', value: 'GT', stationcount: '15' },
    { name: 'GU', value: 'GU', stationcount: '3' },
    { name: 'GW', value: 'GW', stationcount: '3' },
    { name: 'GY', value: 'GY', stationcount: '4' },
    { name: 'HK', value: 'HK', stationcount: '3' },
    { name: 'HN', value: 'HN', stationcount: '21' },
    { name: 'HR', value: 'HR', stationcount: '114' },
    { name: 'HT', value: 'HT', stationcount: '10' },
    { name: 'HU', value: 'HU', stationcount: '217' },
    { name: 'ID', value: 'ID', stationcount: '149' },
    { name: 'IE', value: 'IE', stationcount: '114' },
    { name: 'IL', value: 'IL', stationcount: '49' },
    { name: 'IM', value: 'IM', stationcount: '5' },
    { name: 'IN', value: 'IN', stationcount: '253' },
    { name: 'IQ', value: 'IQ', stationcount: '14' },
    { name: 'IR', value: 'IR', stationcount: '22' },
    { name: 'IS', value: 'IS', stationcount: '28' },
    { name: 'IT', value: 'IT', stationcount: '1167' },
    { name: 'JM', value: 'JM', stationcount: '19' },
    { name: 'JO', value: 'JO', stationcount: '12' },
    { name: 'JP', value: 'JP', stationcount: '94' },
    { name: 'KE', value: 'KE', stationcount: '17' },
    { name: 'KG', value: 'KG', stationcount: '2' },
    { name: 'KH', value: 'KH', stationcount: '20' },
    { name: 'KM', value: 'KM', stationcount: '1' },
    { name: 'KP', value: 'KP', stationcount: '2' },
    { name: 'KR', value: 'KR', stationcount: '66' },
    { name: 'KW', value: 'KW', stationcount: '16' },
    { name: 'KY', value: 'KY', stationcount: '5' },
    { name: 'KZ', value: 'KZ', stationcount: '48' },
    { name: 'LA', value: 'LA', stationcount: '1' },
    { name: 'LB', value: 'LB', stationcount: '25' },
    { name: 'LC', value: 'LC', stationcount: '8' },
    { name: 'LI', value: 'LI', stationcount: '5' },
    { name: 'LK', value: 'LK', stationcount: '24' },
    { name: 'LT', value: 'LT', stationcount: '50' },
    { name: 'LU', value: 'LU', stationcount: '28' },
    { name: 'LV', value: 'LV', stationcount: '63' },
    { name: 'LY', value: 'LY', stationcount: '12' },
    { name: 'MA', value: 'MA', stationcount: '67' },
    { name: 'MC', value: 'MC', stationcount: '6' },
    { name: 'MD', value: 'MD', stationcount: '43' },
    { name: 'ME', value: 'ME', stationcount: '11' },
    { name: 'MG', value: 'MG', stationcount: '8' },
    { name: 'MK', value: 'MK', stationcount: '6' },
    { name: 'ML', value: 'ML', stationcount: '5' },
    { name: 'MM', value: 'MM', stationcount: '11' },
    { name: 'MN', value: 'MN', stationcount: '8' },
    { name: 'MO', value: 'MO', stationcount: '1' },
    { name: 'MQ', value: 'MQ', stationcount: '4' },
    { name: 'MT', value: 'MT', stationcount: '22' },
    { name: 'MU', value: 'MU', stationcount: '4' },
    { name: 'MW', value: 'MW', stationcount: '3' },
    { name: 'MX', value: 'MX', stationcount: '196' },
    { name: 'MY', value: 'MY', stationcount: '13' },
    { name: 'MZ', value: 'MZ', stationcount: '6' },
    { name: 'NA', value: 'NA', stationcount: '8' },
    { name: 'NC', value: 'NC', stationcount: '3' },
    { name: 'NG', value: 'NG', stationcount: '16' },
    { name: 'NI', value: 'NI', stationcount: '13' },
    { name: 'NL', value: 'NL', stationcount: '392' },
    { name: 'NO', value: 'NO', stationcount: '110' },
    { name: 'NP', value: 'NP', stationcount: '7' },
    { name: 'NZ', value: 'NZ', stationcount: '63' },
    { name: 'OM', value: 'OM', stationcount: '5' },
    { name: 'PA', value: 'PA', stationcount: '14' },
    { name: 'PE', value: 'PE', stationcount: '127' },
    { name: 'PF', value: 'PF', stationcount: '1' },
    { name: 'PG', value: 'PG', stationcount: '4' },
    { name: 'PH', value: 'PH', stationcount: '15' },
    // { name: 'PK', value: 'PK', stationcount: '23' },
    { name: 'PL', value: 'PL', stationcount: '732' },
    { name: 'PR', value: 'PR', stationcount: '23' },
    { name: 'PS', value: 'PS', stationcount: '12' },
    { name: 'PT', value: 'PT', stationcount: '221' },
    { name: 'PY', value: 'PY', stationcount: '19' },
    { name: 'QA', value: 'QA', stationcount: '7' },
    { name: 'RE', value: 'RE', stationcount: '1' },
    { name: 'RO', value: 'RO', stationcount: '193' },
    { name: 'RS', value: 'RS', stationcount: '115' },
    { name: 'RU', value: 'RU', stationcount: '957' },
    { name: 'RW', value: 'RW', stationcount: '4' },
    { name: 'SA', value: 'SA', stationcount: '22' },
    { name: 'SC', value: 'SC', stationcount: '8' },
    { name: 'SD', value: 'SD', stationcount: '2' },
    { name: 'SE', value: 'SE', stationcount: '109' },
    { name: 'SG', value: 'SG', stationcount: '28' },
    { name: 'SH', value: 'SH', stationcount: '1' },
    { name: 'SI', value: 'SI', stationcount: '40' },
    { name: 'SK', value: 'SK', stationcount: '81' },
    { name: 'SL', value: 'SL', stationcount: '4' },
    { name: 'SM', value: 'SM', stationcount: '5' },
    { name: 'SN', value: 'SN', stationcount: '9' },
    { name: 'SR', value: 'SR', stationcount: '4' },
    { name: 'SS', value: 'SS', stationcount: '1' },
    { name: 'SV', value: 'SV', stationcount: '9' },
    { name: 'SY', value: 'SY', stationcount: '15' },
    { name: 'SZ', value: 'SZ', stationcount: '1' },
    { name: 'TC', value: 'TC', stationcount: '2' },
    { name: 'TG', value: 'TG', stationcount: '1' },
    { name: 'TH', value: 'TH', stationcount: '78' },
    { name: 'TJ', value: 'TJ', stationcount: '2' },
    { name: 'TM', value: 'TM', stationcount: '5' },
    { name: 'TN', value: 'TN', stationcount: '37' },
    { name: 'TO', value: 'TO', stationcount: '1' },
    { name: 'TR', value: 'TR', stationcount: '155' },
    { name: 'TT', value: 'TT', stationcount: '17' },
    { name: 'TW', value: 'TW', stationcount: '46' },
    { name: 'TZ', value: 'TZ', stationcount: '5' },
    { name: 'UA', value: 'UA', stationcount: '147' },
    { name: 'UG', value: 'UG', stationcount: '8' },
    { name: 'UM', value: 'UM', stationcount: '1' },
    { name: 'US', value: 'US', stationcount: '3684' },
    { name: 'UY', value: 'UY', stationcount: '51' },
    { name: 'UZ', value: 'UZ', stationcount: '3' },
    { name: 'VA', value: 'VA', stationcount: '12' },
    { name: 'VC', value: 'VC', stationcount: '7' },
    { name: 'VE', value: 'VE', stationcount: '30' },
    { name: 'VI', value: 'VI', stationcount: '13' },
    { name: 'VN', value: 'VN', stationcount: '40' },
    { name: 'VU', value: 'VU', stationcount: '1' },
    { name: 'XK', value: 'XK', stationcount: '13' },
    { name: 'YE', value: 'YE', stationcount: '2' },
    { name: 'YT', value: 'YT', stationcount: '1' },
    { name: 'ZA', value: 'ZA', stationcount: '57' },
    { name: 'ZM', value: 'ZM', stationcount: '2' },
    { name: 'ZW', value: 'ZW', stationcount: '10' },
  ],
  STATIONS_BLACKLIST: {
    119353: true,
  },
  STATIONS_CUSTOM: {
    FR: [
      {
        changeuuid: 'splitcloud_1',
        stationuuid: 'splitcloud_1',
        name: 'SkyRock',
        url: 'https://icecast.skyrock.net/s/natio_aac_96k',
        homepage: 'http://skyrock.fm/',
        favicon: 'https://skyrock.fm/layouts/frontoffice/images/skyrock.png',
        tags: 'hiphop,rap,trap,urban,french',
        country: 'France',
        countrycode: 'FR',
        state: 'France',
        language: 'french',
        votes: '284',
        negativevotes: '0',
        lastchangetime: '2019-01-22 08:25:34',
        ip: '124.235.203.72',
        codec: 'ACC',
        bitrate: '0',
        hls: '1',
        lastcheckok: '1',
        lastchecktime: '2019-11-25 17:53:17',
        lastcheckoktime: '2019-11-25 17:53:17',
        clicktimestamp: '2019-11-25 19:49:58',
        clickcount: '0',
        clicktrend: '0',
      },
    ],
    IT: [
      {
        changeuuid: 'splitcloud_2',
        stationuuid: 'splitcloud_2',
        name: 'TRX Radio',
        url: 'https://stream.radio.co/s91647c554/listen',
        homepage: 'https://play.trxradio.it/',
        favicon: 'https://play.trxradio.it/favicon.png',
        tags: 'hiphop,rap,trap,urban,rnb',
        country: 'Italy',
        countrycode: 'IT',
        state: 'Italy',
        language: 'italian',
        votes: '284',
        negativevotes: '0',
        lastchangetime: '2019-01-22 08:25:34',
        ip: '104.128.230.61',
        codec: 'ACC',
        bitrate: '128',
        hls: '1',
        lastcheckok: '1',
        lastchecktime: '2019-11-25 17:53:17',
        lastcheckoktime: '2019-11-25 17:53:17',
        clicktimestamp: '2019-11-25 19:49:58',
        clickcount: '0',
        clicktrend: '0',
      },
    ],
  },
};
